project:
  type: website
  output-dir: docs

execute:
  python: venv/bin/python

website:
  title: "Economic Pulse"
  navbar:
    background: primary
    foreground: light
    logo: fred-logo.svg
    left:
      - text: "Home"
        href: index.html
      - text: "Markets"
        href: SP500.html
      - text: "Macro"
        href: cpi.html
      - text: "About"
        href: about.html
  page-footer: "A Between The Pipes Project"

format:
  html:
    theme: cosmo